const READY = 'READY';
const USER_UPDATE = 'USER_UPDATE';
const USER_SETTINGS_UPDATE = 'USER_SETTINGS_UPDATE';
const PRESENCE_UPDATE = 'PRESENCE_UPDATE';
const MESSAGE_CREATE = 'MESSAGE_CREATE';
const MESSAGE_UPDATE = 'MESSAGE_UPDATE';
const MESSAGE_DELETE = 'MESSAGE_DELETE';
const MESSAGE_REACTION_ADD    = 'MESSAGE_REACTION_ADD';
const MESSAGE_REACTION_REMOVE = 'MESSAGE_REACTION_REMOVE';
const GUILD_MEMBER_ADD    = 'GUILD_MEMBER_ADD';
const GUILD_MEMBER_UPDATE = 'GUILD_MEMBER_UPDATE';
const GUILD_MEMBER_REMOVE = 'GUILD_MEMBER_REMOVE';
const GUILD_ROLE_CREATE = 'GUILD_ROLE_CREATE';
const GUILD_ROLE_UPDATE = 'GUILD_ROLE_UPDATE';
const GUILD_ROLE_DELETE = 'GUILD_ROLE_DELETE';
const GUILD_EMOJI_ADD    = 'GUILD_EMOJI_ADD';
const GUILD_EMOJI_UPDATE = 'GUILD_EMOJI_UPDATE';
const GUILD_EMOJI_REMOVE = 'GUILD_EMOJI_REMOVE';
const CHANNEL_CREATE = 'CHANNEL_CREATE';
const CHANNEL_UPDATE = 'CHANNEL_UPDATE';
const CHANNEL_DELETE = 'CHANNEL_DELETE';
const GUILD_CREATE = 'GUILD_CREATE';
const GUILD_UPDATE = 'GUILD_UPDATE';
const GUILD_DELETE = 'GUILD_DELETE';
const GUILD_SYNC   = 'GUILD_SYNC';
const GUILD_EMOJIS_UPDATE = 'GUILD_EMOJIS_UPDATE';
const GUILD_MEMBERS_CHUNK = 'GUILD_MEMBERS_CHUNK';
const VOICE_STATE_UPDATE  = 'VOICE_STATE_UPDATE';
const VOICE_SERVER_UPDATE = 'VOICE_SERVER_UPDATE';

const CLIENT_EVENTS   = [READY,USER_UPDATE,USER_SETTINGS_UPDATE];
const USER_EVENTS     = [PRESENCE_UPDATE];
const MESSAGE_EVENTS  = [MESSAGE_CREATE,MESSAGE_UPDATE,MESSAGE_DELETE];
const REACTION_EVENTS = [MESSAGE_REACTION_ADD,MESSAGE_REACTION_REMOVE];
const MEMBER_EVENTS   = [GUILD_MEMBER_ADD,GUILD_MEMBER_UPDATE,GUILD_MEMBER_REMOVE];
const ROLE_EVENTS     = [GUILD_ROLE_CREATE,GUILD_ROLE_UPDATE,GUILD_ROLE_DELETE];
const EMOJI_EVENTS    = [GUILD_EMOJI_ADD,GUILD_EMOJI_UPDATE,GUILD_EMOJI_REMOVE];
const CHANNEL_EVENTS  = [CHANNEL_CREATE,CHANNEL_UPDATE,CHANNEL_DELETE];
const GUILD_EVENTS    = [GUILD_CREATE,GUILD_UPDATE,GUILD_DELETE,GUILD_SYNC,GUILD_EMOJIS_UPDATE,GUILD_MEMBERS_CHUNK];
const VOICE_EVENTS    = [VOICE_STATE_UPDATE,VOICE_SERVER_UPDATE];

module.exports = {
    READY,
    MESSAGE_CREATE,
    MESSAGE_UPDATE,
    MESSAGE_REACTION_ADD,
    MESSAGE_REACTION_REMOVE,
    PRESENCE_UPDATE,
    USER_UPDATE,
    USER_SETTINGS_UPDATE,
    GUILD_CREATE,
    GUILD_UPDATE,
    GUILD_DELETE,
    GUILD_MEMBER_ADD,
    GUILD_MEMBER_UPDATE,
    GUILD_MEMBER_REMOVE,
    GUILD_ROLE_CREATE,
    GUILD_ROLE_UPDATE,
    GUILD_ROLE_DELETE,
    CHANNEL_CREATE,
    CHANNEL_UPDATE,
    CHANNEL_DELETE,
    GUILD_EMOJIS_UPDATE,
    VOICE_STATE_UPDATE,
    VOICE_SERVER_UPDATE,
    GUILD_MEMBERS_CHUNK,
    GUILD_SYNC,

    CLIENT_EVENTS,
    USER_EVENTS,
    MESSAGE_EVENTS,
    REACTION_EVENTS,
    MEMBER_EVENTS,
    ROLE_EVENTS,
    EMOJI_EVENTS,
    CHANNEL_EVENTS,
    GUILD_EVENTS,
    VOICE_EVENTS
};
